name = "SimpleExpressions"
uuid = "deba94f7-f32a-40ad-b45e-be020a5ded2f"
authors = ["jverzani <jverzani@gmail.com> and contributors"]
version = "1.0.14"

[weakdeps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[extensions]
SimpleExpressionsSpecialFunctionsExt = "SpecialFunctions"
SimpleExpressionsTermInterfaceExt = "TermInterface"

[compat]
SpecialFunctions = "1,2"
TermInterface = "0.3.3"
julia = "1.9"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
