name = "SimpleExpressions"
uuid = "deba94f7-f32a-40ad-b45e-be020a5ded2f"
authors = ["jverzani <jverzani@gmail.com> and contributors"]
version = "1.0.20"

[deps]

[weakdeps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[extensions]
SimpleExpressionsAbstractTreesExt = "AbstractTrees"
SimpleExpressionsRecipesBaseExt = "RecipesBase"
SimpleExpressionsRootsExt = "Roots"
SimpleExpressionsSpecialFunctionsExt = "SpecialFunctions"
SimpleExpressionsTermInterfaceExt = "TermInterface"

[compat]
AbstractTrees = "0.4"
RecipesBase = "1"
Roots = "2"
SpecialFunctions = "1,2"
TermInterface = "0.3.3, 1, 2"
julia = "1.9"

[extras]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
