name = "SimpleExpressions"
uuid = "deba94f7-f32a-40ad-b45e-be020a5ded2f"
authors = ["jverzani <jverzani@gmail.com> and contributors"]
version = "1.1.5"

[deps]
CallableExpressions = "391672e0-bbe4-4ab4-8bc9-b89a79cbc2f0"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CommonEq = "3709ef60-1bee-4518-9f2f-acd86f176c50"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[weakdeps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
#Metatheory = "e9d8d322-4543-424a-9be4-0cc815abe26c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[extensions]
SimpleExpressionsAbstractTreesExt = "AbstractTrees"
SimpleExpressionsLatexifyExt = "Latexify"
#SimpleExpressionsMetatheoryExt = "Metatheory"
SimpleExpressionsRecipesBaseExt = "RecipesBase"
SimpleExpressionsRootsExt = "Roots"
SimpleExpressionsSpecialFunctionsExt = "SpecialFunctions"

[compat]
AbstractTrees = "0.4"
CallableExpressions = "1.0.0"
Combinatorics = "1.0.2"
CommonEq = "0.2.1"
CommonSolve = "0.2.4"
Latexify = "0.16, 1"
#Metatheory = "2, 3"
RecipesBase = "1"
Roots = "2"
SpecialFunctions = "1,2"
TermInterface = "2,3"
julia = "1.10"

[extras]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
